spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwt_security
    username: root
    password: Test@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect